version: "3.8"

services:
  # mongodb:
  #   image: mongo:latest
  #   container_name: mini_mongodb
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
  #   ports:
  #     - "${MONGODB_PORT}:27017"
  #   volumes:
  #     - mongodb_data:/data/db
  #   networks:
  #     - mini_network

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data

volumes:
  mongodb_data:
  valkey_data:

networks:
  mini_network:
    driver: bridge
