version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mini_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mini_network

  redis:
    image: redis:latest
    container_name: mini_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - mini_network

volumes:
  postgres_data:
  redis_data:

networks:
  mini_network:
    driver: bridge